name: Build LibTorchVision

on:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: windows-latest

    steps:
      
      - run: |
          git clone https://github.com/pytorch/vision
          cd vision
          git checkout v0.10.0
      
      - name: Set up Python
        uses: actions/setup-python@v2
      
      - name: Download LibTorch
        run: |
          from urllib.request import urlretrieve
          url = 'https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.9.0%2Bcpu.zip'
          dst = 'libtorch.zip'
          urlretrieve(url, dst)
        shell: python
        
      - name: Extract
        run: |
          import zipfile
          with zipfile.ZipFile("libtorch.zip","r") as zip_ref:
            zip_ref.extractall(".")
        shell: python
        
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
        
      - name: Install conda dependencies
        run: |
          conda install libpng jpeg
          
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[16.4,16.5)'
          
      - run: | 
          ls
          cd vision
          mkdir build
          cd build
          cmake .. -D"CMAKE_PREFIX_PATH=../libtorch"
          msbuild "-p:Configuration=Release" "-p:BuildInParallel=true" "-p:MultiProcessorCompilation=true" "-p:CL_MPCount=4" torchvision.vcxproj -maxcpucount:4
          msbuild "-p:Configuration=Release" "-p:BuildInParallel=true" "-p:MultiProcessorCompilation=true" "-p:CL_MPCount=4" INSTALL.vcxproj -maxcpucount:4
          ls
          ls Release
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: vision\build\Release\torchvision.dll
          name: v0.10.0 
          tag_name: v0.10.0
          
